[mgr]
prepend_keymap = [
  { on = "<S-j>", run = "arrow 5", desc = "5j" },
  { on = "<S-k>", run = "arrow -5", desc = "tk" },
  { on = "z", run = "noop" },
  { on = "Z", run = "noop" },
  { on = "s", run = "noop" },
  { on = "S", run = "noop" },
  { on = "<D-p>", run = "search fd", desc = "Search files by name with fd" },
  { on = "<D-S-f>", run = "search rg", desc = "Search files by content with ripgrep" },
  { on = [
    "g",
    "t",
  ], run = "plugin zoxide", desc = "zoxide" },
  { on = "z", run = "plugin fzf", desc = "fzf search files" },
  { on = [
    "g",
    "d",
  ], run = "cd ~/Downloads", desc = "Go to Downloads" },
  { on = [
    "g",
    "v",
  ], run = "cd ~/.config/nvim", desc = "Go to Neovim config" },
  { on = [
    "g",
    "/",
  ], run = "cd ~", desc = "go home" },
]
