[mgr]
prepend_keymap = [
  { on = "<S-j>", run = "arrow 5", desc = "5j" },
  { on = "<S-k>", run = "arrow -5", desc = "tk" },
  { on = [
    "g",
    "d",
  ], run = "cd ~/Downloads", desc = "Go to Downloads" },
  { on = [
    "g",
    "v",
  ], run = "cd ~/.config/nvim", desc = "Go to Neovim config" },
  { on = [
    "g",
    "/",
  ], run = "cd ~", desc = "go home" },
]
