[mgr]
cwd = { fg = "cyan" }
syntect_theme = "~/dotfiles/yazi/CiapreBlack.tmTheme"
hovered = { fg = "black", bg = "lightblue" }

# Find
find_keyword = { fg = "yellow", italic = true }
find_position = { fg = "magenta", bg = "darkgray", italic = true }

# Marker
marker_selected = { fg = "lightgreen", bg = "lightgreen" }
marker_copied = { fg = "lightyellow", bg = "lightyellow" }
marker_cut = { fg = "lightred", bg = "lightred" }

border_style = { fg = "blue" }
