os:
  editPreset: "nvim"
  editAtLine: "nvim +{{line}} {{filename}}"
gui:
  sidePanelWidth: 0.25 #左侧面板宽度 (0 - 1.0)
  showFileTree: false
  nerdFontsVersion: "3"
  branchColorPatterns:
    "^feature/": "#00ff00"
    "^refactor/": "cyan"
    "^bugfix/": "#FF6B6B"
    "^master$": "yellow"
    "^main$": "yellow"
    "^uat$": "yellow"
    "^dev$": "yellow"
  theme:
    # Border color of focused window
    activeBorderColor:
      - green
      - bold
    # Border color of non-focused windows
    inactiveBorderColor:
      - default
    # Border color of focused window when searching in that window
    searchingActiveBorderColor:
      - cyan
      - bold
    # Color of keybindings help text in the bottom line
    optionsTextColor:
      - blue
    # Background color of selected line.
    # See https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md#highlighting-the-selected-line
    selectedLineBgColor:
      - cyan
    # Background color of selected line when view doesn't have focus.
    inactiveViewSelectedLineBgColor:
      - bold
    # Foreground color of copied commit
    cherryPickedCommitFgColor:
      - blue
    # Background color of copied commit
    cherryPickedCommitBgColor:
      - cyan
    # Foreground color of marked base commit (for rebase)
    markedBaseCommitFgColor:
      - blue
    # Background color of marked base commit (for rebase)
    markedBaseCommitBgColor:
      - yellow
    # Color for file with unstaged changes
    unstagedChangesColor:
      - red
    # Default text color
    defaultFgColor:
      - default
# Config relating to git
git:
  pagers:
    - colorArg: always
      pager: "delta --dark --paging=never"
      useConfig: false
      externalDiffCommand: ""
  # Command used when displaying the current branch git log in the main window
  branchLogCmd: "git log --graph --color=always --abbrev-commit --decorate --date=format:'%Y-%m-%d %H:%M:%S' --pretty=format:'%C(yellow)%h%Creset %C(white)-%Creset %C(bold magenta)%an%Creset %C(white)-%Creset %C(cyan)%ad%Creset %C(white)-%Creset %C(bold green)%s%Creset' {{branchName}}"
  # Commands used to display git log of all branches in the main window, they will be cycled in order of appearance (array of strings)
  allBranchesLogCmds:
    - "git log --graph --color=always --abbrev-commit --decorate --date=format:'%Y-%m-%d %H:%M:%S' --pretty=format:'%C(yellow)%h%Creset %C(white)-%Creset %C(bold magenta)%an%Creset %C(white)-%Creset %C(cyan)%ad%Creset %C(white)-%Creset %C(bold green)%s%Creset'"
